apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
data:
  index.html: |
    <html>
      <head><title>App1</title></head>
      <body>
        <h1 style="text-align: center; font-size: 72px;">APP1</h1>
      </body>
    </html>