apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
data:
  index.html: |
    <html>
      <head><title>App2</title></head>
      <body>
        <h1 style="text-align: center; font-size: 72px;">APP2</h1>
      </body>
    </html>