apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-html
data:
  index.html: |
    <html>
      <head><title>App3</title></head>
      <body>
        <h1 style="text-align: center; font-size: 72px;">APP3</h1>
      </body>
    </html>